name: gwid

description: Альтернативный FOSS клиент для мессенджера MAX.

# Версия приложения и номер сборки
version: 0.4.1+9

repository: https://github.com/KometTeam/Komet

# Предотвращение случайной публикации в pub
publish_to: none

environment:
  # Поддерживаются версии Dart SDK от 3.10 до 4.0.
  # Рекомендуется обновлять только минорную компоненту версии.
  sdk: ^3.10.0

  # Поддерживаются версии Flutter от 3.38.
  flutter: ">=3.38.0"

dependencies:
  # SDK зависимости
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Hosted зависимости
  dynamic_color: ^1.7.0
  pinput: ^4.0.0
  mask_text_input_formatter: ^2.9.0
  web_socket_channel: ^2.4.0
  uuid: ^4.4.0
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  battery_plus: ^6.0.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  http: ^1.5.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  scrollable_positioned_list: ^0.3.8
  socks5_proxy: ^2.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_timezone: ^5.0.0
  timezone: ^0.10.1
  file_picker: ^10.3.3
  permission_handler: ^11.3.1
  image: ^4.1.7
  encrypt: ^5.0.3
  google_fonts: ^6.2.1
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  flutter_background_service: ^5.0.1
  flutter_local_notifications: ^19.5.0
  wakelock_plus: ^1.2.8
  flutter_markdown: ^0.7.7
  video_player: ^2.9.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  es_compression: ^2.0.14
  msgpack_dart: ^1.0.1
  ffi: ^2.1.0
  disable_battery_optimization: ^1.1.2
  flutter_highlight: ^0.7.0
  flutter_linkify: ^6.0.0
  app_links: ^6.4.1
  open_file: ^3.5.2
  flutter_secure_storage: ^9.2.4
  flutter_inappwebview: ^6.1.5
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  chewie: ^1.7.5
  just_audio: ^0.9.40
  platform_info: ^5.0.0

dev_dependencies:
  # SDK зависимости
  flutter_test:
    sdk: flutter

  # Hosted зависимости
  flutter_lints: ^6.0.0

# Конфигурация Flutter.
flutter:
  # Рекомендуется использовать фреймворк для i18n вместо встроенного во Flutter.
  generate: false

  # Включает библиотеку flutter/material.
  uses-material-design: true

  # Ресурсы, которые прилагаются к приложению без сжатия или шифрования.
  assets:
    - assets/images/
    - assets/icon/

# Конфирурация генератора иконок приложения.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/komet_512.png"
  adaptive_icon_background: "assets/icon/bg.png"
  adaptive_icon_foreground: "assets/icon/komet_512.png"
  windows:
    generate: true
    image_path: "assets/icon/komet_512.png"
    icon_size: 256
